#!/usr/bin/env bash
# Starts the ComfyUI server in a detached tmux session.
#
#   ./30_serve_comfyui.sh              # start (or report already-running)
#   ./30_serve_comfyui.sh --fg         # foreground, for debugging startup crashes
#   ./30_serve_comfyui.sh --stop
#   ./30_serve_comfyui.sh --restart
#
# Attention backend: --use-pytorch-cross-attention forces SDPA. On Blackwell this
# is the safe default because flash-attn/xformers frequently have no sm_100 wheel
# yet and fall back to a broken or absent kernel. Set COMFY_ATTENTION=auto to let
# ComfyUI choose (faster if a Blackwell flash-attn build is installed). See NOTES.md.

source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

ACTION="start"
FOREGROUND=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --fg) FOREGROUND=1; shift ;;
    --stop) ACTION="stop"; shift ;;
    --restart) ACTION="restart"; shift ;;
    -h|--help) sed -n '2,16p' "$0"; exit 0 ;;
    *) die "unknown argument: $1" ;;
  esac
done

SESSION="${TMUX_SERVER_SESSION}"

stop_server() {
  if tmux has-session -t "${SESSION}" 2>/dev/null; then
    tmux kill-session -t "${SESSION}"
    ok "stopped tmux session '${SESSION}'"
  else
    warn "no tmux session '${SESSION}' to stop"
  fi
}

case "${ACTION}" in
  stop) stop_server; exit 0 ;;
  restart) stop_server; sleep 2 ;;
esac

[[ -d "${COMFY_DIR}" ]] || die "ComfyUI not found at ${COMFY_DIR}. Run 10_install_comfyui.sh first."
PY="$(comfy_python)"

# ---- point ComfyUI at the external model store instead of copying weights ----
EXTRA_PATHS="${COMFY_DIR}/extra_model_paths.yaml"
log "writing ${EXTRA_PATHS} -> ${MODELS_DIR}"
cat > "${EXTRA_PATHS}" <<EOF
# Generated by 30_serve_comfyui.sh — edits are overwritten on each start.
b200:
  base_path: ${MODELS_DIR}
  is_default: true
  checkpoints: |
    ltx
    wan
  diffusion_models: |
    ltx
    wan
  unet: |
    ltx
    wan
  text_encoders: |
    text_encoders
    text_encoders/t5xxl
  clip: |
    text_encoders
  vae: |
    ltx
    wan
    vae
  upscale_models: |
    upscale_models
  loras: |
    loras
EOF

ARGS=(--listen "${COMFY_HOST}" --port "${COMFY_PORT}" --output-directory "${B200_WORKDIR}/output")
case "${COMFY_ATTENTION:-sdpa}" in
  sdpa) ARGS+=(--use-pytorch-cross-attention) ;;
  auto) : ;;
  *) warn "unknown COMFY_ATTENTION='${COMFY_ATTENTION}', using ComfyUI's default" ;;
esac
# 180GB HBM3e — keep everything resident rather than offloading between steps.
ARGS+=(${COMFY_EXTRA_ARGS:---highvram})

mkdir -p "${B200_WORKDIR}/output" "${B200_WORKDIR}/logs"

if (( FOREGROUND )); then
  log "starting ComfyUI in foreground: ${PY} main.py ${ARGS[*]}"
  cd "${COMFY_DIR}" && exec "${PY}" main.py "${ARGS[@]}"
fi

if tmux has-session -t "${SESSION}" 2>/dev/null; then
  warn "tmux session '${SESSION}' already running — use --restart to replace it"
else
  LOG="${B200_WORKDIR}/logs/comfyui-$(date +%Y%m%d-%H%M%S).log"
  tmux new-session -d -s "${SESSION}" -c "${COMFY_DIR}" \
    "script -q -e -c '$(printf '%q ' "${PY}" main.py "${ARGS[@]}")' '${LOG}'"
  ok "started tmux session '${SESSION}' (log: ${LOG})"
  ln -sfn "${LOG}" "${B200_WORKDIR}/logs/comfyui-latest.log"
fi

wait_for_comfy 300

URL="$(comfy_url)"
echo
cat <<EOF
  ComfyUI listening on ${COMFY_HOST}:${COMFY_PORT}

  Local / tunnelled browser access:
    ssh -N -L ${COMFY_PORT}:127.0.0.1:${COMFY_PORT} <user>@<b200-host>
    then open http://127.0.0.1:${COMFY_PORT}

  ComfyUI ships no authentication. Only bind 0.0.0.0 on a trusted network,
  and prefer the SSH tunnel above over exposing the port.

  watch logs   tmux attach -t ${SESSION}      (detach: Ctrl-b then d)
               tail -f ${B200_WORKDIR}/logs/comfyui-latest.log
  health       curl -s ${URL}/system_stats | jq .
  stop         $0 --stop

  next: ${B200_ROOT}/scripts/40_smoke_test.sh
EOF
